# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Verify .NET Tests

env:
  DOTNET_VERSION: '8.0.x'                 # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore ./src/Playground/Playground.sln
    - name: Build
      run: dotnet build --no-restore ./src/Playground/Playground.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Playground/Playground.sln
